services:
  db:
    image: postgres:12.2-alpine
    container_name: "comments-database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Post@123
      - SSL_MODE=disable
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data
    #healthcheck:
    #  test: ["CMD-SHELL", "pg_isready"]
    #  interval: 10s
    #  timeout: 5s
    #  retries: 5  
  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret@123
    ports:
      - "5050:80"
    networks:
      - fullstack  

  api:
    build: .
    container_name: "comments-rest-api"
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=Post@123
      - DB_DB=postgres
      - DB_HOST=db
      - DB_TABLE=postgres
      - DB_PORT=5432
      - SSL_MODE=disable
    ports:
      - "8080:8080"
    depends_on:
      - db
    #      condition: service_healthy
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge